<?php

declare(strict_types=1);

use App\Http\Controllers\AgendamentoController;
use App\Http\Controllers\AgendamentoPublicoController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Auth\PasswordResetController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\AvaliacaoController;
use App\Http\Controllers\BloqueioController;
use App\Http\Controllers\CalendarioController;
use App\Http\Controllers\CargoController;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\ConfiguracaoController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Dev\DevLoginController;
use App\Http\Controllers\FinanceiroController;
use App\Http\Controllers\HorarioTrabalhoController;
use App\Http\Controllers\NotificacaoController;
use App\Http\Controllers\PdvController;
use App\Http\Controllers\PerfilController;
use App\Http\Controllers\PermissaoController;
use App\Http\Controllers\PlansController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\ProdutoController;
use App\Http\Controllers\ProfissionalController;
use App\Http\Controllers\RelatorioController;
use App\Http\Controllers\ServicoController;
use App\Http\Controllers\SitePublicoController;
use App\Http\Middleware\SetTenantMiddleware;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
    Route::post('/login', [AuthController::class, 'login']);
    Route::get('/register', [RegisterController::class, 'show'])->name('register');
    Route::post('/register', [RegisterController::class, 'store']);
    Route::view('/recuperar-senha', 'auth.recover')->name('password.request');
    Route::post('/recuperar-senha/enviar-codigo', [PasswordResetController::class, 'sendCode'])->name('password.send-code');
    Route::post('/recuperar-senha/verificar-codigo', [PasswordResetController::class, 'verifyCode'])->name('password.verify-code');
    Route::post('/recuperar-senha/redefinir', [PasswordResetController::class, 'resetPassword'])->name('password.reset-custom');
});

Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth')->name('logout');

Route::middleware(['auth', SetTenantMiddleware::class])->group(function () {
    Route::get('/', fn () => redirect()->route('dashboard'));
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/dashboard/resumo', [DashboardController::class, 'resumo'])->name('dashboard.resumo');
    Route::get('/dashboard/alertas', [DashboardController::class, 'alertas'])->name('dashboard.alertas');
    Route::get('/dashboard/receita', [DashboardController::class, 'receita'])->name('dashboard.receita');
    Route::get('/dashboard/kanban', [DashboardController::class, 'kanban'])->name('dashboard.kanban');

    Route::get('agendamentos/resumo-hoje', [AgendamentoController::class, 'resumoHoje'])->name('agendamentos.resumo-hoje');
    Route::get('agendamentos/hoje', [AgendamentoController::class, 'hoje'])->name('agendamentos.hoje');
    Route::get('agendamentos/buscar', [AgendamentoController::class, 'buscar'])->name('agendamentos.buscar');
    Route::get('agendamentos/exportar', [AgendamentoController::class, 'exportarCsv'])->name('agendamentos.exportar');
    Route::get('agendamentos/proximos', [AgendamentoController::class, 'proximos'])->name('agendamentos.proximos');
    Route::get('agendamentos/cancelados', [AgendamentoController::class, 'cancelados'])->name('agendamentos.cancelados');
    Route::get('agendamentos/pendentes', [AgendamentoController::class, 'pendentes'])->name('agendamentos.pendentes');
    Route::get('agendamentos/em-atendimento', [AgendamentoController::class, 'emAtendimento'])->name('agendamentos.em-atendimento');
    Route::get('agendamentos/agenda', [AgendamentoController::class, 'agenda'])->name('agendamentos.agenda');
    Route::patch('agendamentos/bulk-status', [AgendamentoController::class, 'bulkStatus'])->name('agendamentos.bulk-status');
    Route::resource('agendamentos', AgendamentoController::class);
    Route::post('agendamentos/{agendamento}/duplicar', [AgendamentoController::class, 'duplicar'])->name('agendamentos.duplicar');
    Route::patch('agendamentos/{agendamento}/status', [AgendamentoController::class, 'updateStatus'])->name('agendamentos.updateStatus');
    Route::patch('agendamentos/{agendamento}/move', [AgendamentoController::class, 'move'])->name('agendamentos.move');
    Route::get('agendamentos/{agendamento}/json', [AgendamentoController::class, 'detalhe'])->name('agendamentos.detalhe');
    Route::get('agendamentos/{agendamento}/historico-cliente', [AgendamentoController::class, 'historicoCliente'])->name('agendamentos.historico-cliente');
    Route::patch('agendamentos/{agendamento}/observacao', [AgendamentoController::class, 'observacao'])->name('agendamentos.observacao');
    Route::patch('agendamentos/{agendamento}/valor', [AgendamentoController::class, 'valor'])->name('agendamentos.valor');
    Route::patch('agendamentos/{agendamento}/duracao', [AgendamentoController::class, 'duracao'])->name('agendamentos.duracao');
    Route::patch('agendamentos/{agendamento}/profissional', [AgendamentoController::class, 'reassignarProfissional'])->name('agendamentos.profissional');
    Route::patch('agendamentos/{agendamento}/servico', [AgendamentoController::class, 'reassignarServico'])->name('agendamentos.servico');
    Route::patch('agendamentos/{agendamento}/cliente', [AgendamentoController::class, 'reassignarCliente'])->name('agendamentos.cliente');
    Route::get('agendamentos/{agendamento}/avaliacao', [AgendamentoController::class, 'getAvaliacao'])->name('agendamentos.avaliacao.get');
    Route::post('agendamentos/{agendamento}/avaliacao', [AgendamentoController::class, 'avaliacao'])->name('agendamentos.avaliacao');
    Route::patch('avaliacoes/{avaliacao}', [AvaliacaoController::class, 'update'])->name('avaliacoes.update');
    Route::delete('avaliacoes/{avaliacao}', [AvaliacaoController::class, 'destroy'])->name('avaliacoes.destroy');
    Route::get('calendario', [CalendarioController::class, 'index'])->name('calendario');
    Route::get('relatorios', [RelatorioController::class, 'index'])->name('relatorios');
    Route::get('relatorios/exportar', [RelatorioController::class, 'exportarCsv'])->name('relatorios.exportar');
    Route::get('relatorios/fidelidade/exportar', [RelatorioController::class, 'exportarFidelidadeCsv'])->name('relatorios.fidelidade.exportar');
    Route::get('relatorios/comissoes/exportar', [RelatorioController::class, 'exportarComissoesCsv'])->name('relatorios.comissoes.exportar');
    Route::get('relatorios/avaliacoes', [RelatorioController::class, 'avaliacoesJson'])->name('relatorios.avaliacoes');
    Route::get('relatorios/clientes', [RelatorioController::class, 'clientesJson'])->name('relatorios.clientes');
    Route::get('relatorios/servicos', [RelatorioController::class, 'servicosJson'])->name('relatorios.servicos');
    Route::get('relatorios/avaliacoes/exportar', [RelatorioController::class, 'exportarAvaliacoesCsv'])->name('relatorios.avaliacoes.exportar');
    Route::get('relatorios/profissionais', [RelatorioController::class, 'profissionaisJson'])->name('relatorios.profissionais');
    Route::get('relatorios/ocupacao', [RelatorioController::class, 'ocupacaoJson'])->name('relatorios.ocupacao');
    Route::get('relatorios/comissoes/json', [RelatorioController::class, 'comissoesJson'])->name('relatorios.comissoes.json');
    Route::get('relatorios/heatmap', [RelatorioController::class, 'heatmap'])->name('relatorios.heatmap');
    Route::get('relatorios/produtos-mais-vendidos', [RelatorioController::class, 'produtosMaisVendidos'])->name('relatorios.produtos-mais-vendidos');
    Route::get('relatorios/horarios-pico', [RelatorioController::class, 'horariosPico'])->name('relatorios.horarios-pico');
    Route::get('relatorios/retencao', [RelatorioController::class, 'retencao'])->name('relatorios.retencao');
    Route::get('relatorios/evolucao-semanal', [RelatorioController::class, 'evolucaoSemanal'])->name('relatorios.evolucao-semanal');
    Route::get('relatorios/top-clientes', [RelatorioController::class, 'topClientes'])->name('relatorios.top-clientes');
    Route::get('relatorios/receita-por-dia', [RelatorioController::class, 'receitaPorDia'])->name('relatorios.receita-por-dia');
    Route::get('relatorios/media-ticket', [RelatorioController::class, 'mediaTicket'])->name('relatorios.media-ticket');
    Route::get('relatorios/taxa-cancelamento', [RelatorioController::class, 'taxaCancelamento'])->name('relatorios.taxa-cancelamento');
    Route::get('relatorios/novos-clientes', [RelatorioController::class, 'novosClientes'])->name('relatorios.novos-clientes');
    Route::get('relatorios/churn', [RelatorioController::class, 'churn'])->name('relatorios.churn');
    Route::get('relatorios/receita-mensal', [RelatorioController::class, 'receitaMensal'])->name('relatorios.receita-mensal');
    Route::get('relatorios/por-dia-semana', [RelatorioController::class, 'agendamentosPorDiaSemana'])->name('relatorios.por-dia-semana');
    Route::get('relatorios/ticket-por-hora', [RelatorioController::class, 'ticketPorHora'])->name('relatorios.ticket-por-hora');
    Route::get('financeiro', [FinanceiroController::class, 'index'])->name('financeiro');
    Route::get('financeiro/resumo', [FinanceiroController::class, 'resumo'])->name('financeiro.resumo');
    Route::get('financeiro/fluxo-caixa', [FinanceiroController::class, 'fluxoCaixa'])->name('financeiro.fluxo-caixa');
    Route::get('financeiro/exportar', [FinanceiroController::class, 'exportarCsv'])->name('financeiro.exportar');
    Route::get('produtos/buscar', [ProdutoController::class, 'buscar'])->name('produtos.buscar');
    Route::get('produtos/estoque-baixo', [ProdutoController::class, 'estoqueBaixo'])->name('produtos.estoque-baixo');
    Route::get('produtos/exportar', [ProdutoController::class, 'exportarCsv'])->name('produtos.exportar');
    Route::get('produtos', [ProdutoController::class, 'index'])->name('produtos.index');
    Route::post('produtos', [ProdutoController::class, 'store'])->name('produtos.store');
    Route::get('produtos/{produto}/vendas', [ProdutoController::class, 'vendas'])->name('produtos.vendas');
    Route::get('produtos/{produto}/json', [ProdutoController::class, 'detalhe'])->name('produtos.detalhe');
    Route::put('produtos/{produto}', [ProdutoController::class, 'update'])->name('produtos.update');
    Route::delete('produtos/{produto}', [ProdutoController::class, 'destroy'])->name('produtos.destroy');
    Route::patch('produtos/{produto}/toggle', [ProdutoController::class, 'toggle'])->name('produtos.toggle');
    Route::patch('produtos/{produto}/estoque', [ProdutoController::class, 'estoque'])->name('produtos.estoque');
    Route::patch('produtos/{produto}/preco', [ProdutoController::class, 'preco'])->name('produtos.preco');
    Route::patch('produtos/{produto}/categoria', [ProdutoController::class, 'categoria'])->name('produtos.categoria');
    Route::patch('produtos/{produto}/unidade', [ProdutoController::class, 'unidade'])->name('produtos.unidade');
    Route::patch('produtos/{produto}/sku', [ProdutoController::class, 'sku'])->name('produtos.sku');
    Route::patch('produtos/{produto}/custo', [ProdutoController::class, 'custo'])->name('produtos.custo');
    Route::patch('produtos/{produto}/estoque-min', [ProdutoController::class, 'estoqueMin'])->name('produtos.estoque-min');
    Route::patch('produtos/{produto}/descricao', [ProdutoController::class, 'descricao'])->name('produtos.descricao');
    Route::patch('produtos/{produto}/nome', [ProdutoController::class, 'nome'])->name('produtos.nome');
    Route::post('produtos/{produto}/imagens', [ProdutoController::class, 'storeImagem'])->name('produtos.imagens.store');
    Route::delete('produtos/imagens/{imagem}', [ProdutoController::class, 'destroyImagem'])->name('produtos.imagens.destroy');
    Route::patch('produtos/imagens/{imagem}/capa', [ProdutoController::class, 'setCapa'])->name('produtos.imagens.capa');

    Route::get('pdv', [PdvController::class, 'index'])->name('pdv');
    Route::get('pdv/resumo', [PdvController::class, 'resumo'])->name('pdv.resumo');
    Route::get('pdv/vendas/json', [PdvController::class, 'listarVendas'])->name('pdv.vendas.json');
    Route::get('pdv/produtos/buscar', [PdvController::class, 'buscarProdutos'])->name('pdv.produtos.buscar');
    Route::get('pdv/vendas/{venda}/json', [PdvController::class, 'vendaDetalhe'])->name('pdv.vendas.detalhe');
    Route::get('pdv/exportar', [PdvController::class, 'exportarCsv'])->name('pdv.exportar');
    Route::post('pdv/venda', [PdvController::class, 'store'])->name('pdv.store');
    Route::patch('pdv/vendas/{venda}/observacao', [PdvController::class, 'observacaoVenda'])->name('pdv.vendas.observacao');
    Route::delete('pdv/vendas/{venda}', [PdvController::class, 'destroyVenda'])->name('pdv.vendas.destroy');

    Route::get('portfolio', [PortfolioController::class, 'index'])->name('portfolio.index');

    Route::get('cargos/json', [CargoController::class, 'listar'])->name('cargos.json');
    Route::get('cargos', [CargoController::class, 'index'])->name('cargos.index');
    Route::post('cargos', [CargoController::class, 'store'])->name('cargos.store');
    Route::put('cargos/{cargo}', [CargoController::class, 'update'])->name('cargos.update');
    Route::get('cargos/{cargo}/json', [CargoController::class, 'detalhe'])->name('cargos.detalhe');
    Route::get('cargos/{cargo}/profissionais', [CargoController::class, 'profissionais'])->name('cargos.profissionais');
    Route::patch('cargos/{cargo}/descricao', [CargoController::class, 'descricao'])->name('cargos.descricao');
    Route::patch('cargos/{cargo}/nome', [CargoController::class, 'nome'])->name('cargos.nome');
    Route::patch('cargos/{cargo}/nivel', [CargoController::class, 'nivel'])->name('cargos.nivel');
    Route::patch('cargos/{cargo}/comissao', [CargoController::class, 'comissao'])->name('cargos.comissao');
    Route::patch('cargos/{cargo}/cor', [CargoController::class, 'cor'])->name('cargos.cor');
    Route::delete('cargos/{cargo}', [CargoController::class, 'destroy'])->name('cargos.destroy');

    Route::get('permissoes', [PermissaoController::class, 'index'])->name('permissoes.index');
    Route::patch('permissoes/usuarios/{user}/role', [PermissaoController::class, 'assignUserRole'])->name('permissoes.users.role');
    Route::patch('permissoes/usuarios/{user}/profissional', [PermissaoController::class, 'assignUserProfissional'])->name('permissoes.users.profissional');

    Route::get('financeiro/categorias', [FinanceiroController::class, 'categorias'])->name('financeiro.categorias');
    Route::get('financeiro/lancamentos/buscar', [FinanceiroController::class, 'buscarLancamentos'])->name('financeiro.lancamentos.buscar');
    Route::get('financeiro/lancamentos/{lancamento}', [FinanceiroController::class, 'showLancamento'])->name('financeiro.lancamentos.show');
    Route::post('financeiro/lancamentos', [FinanceiroController::class, 'storeLancamento'])->name('financeiro.lancamentos.store');
    Route::put('financeiro/lancamentos/{lancamento}', [FinanceiroController::class, 'updateLancamento'])->name('financeiro.lancamentos.update');
    Route::patch('financeiro/lancamentos/{lancamento}/status', [FinanceiroController::class, 'statusLancamento'])->name('financeiro.lancamentos.status');
    Route::patch('financeiro/lancamentos/{lancamento}/categoria', [FinanceiroController::class, 'categoriaLancamento'])->name('financeiro.lancamentos.categoria');
    Route::patch('financeiro/lancamentos/{lancamento}/observacao', [FinanceiroController::class, 'observacaoLancamento'])->name('financeiro.lancamentos.observacao');
    Route::delete('financeiro/lancamentos/{lancamento}', [FinanceiroController::class, 'destroyLancamento'])->name('financeiro.lancamentos.destroy');
    Route::get('site', [SitePublicoController::class, 'index'])->name('site.index');
    Route::put('site/save', [SitePublicoController::class, 'save'])->name('site.save');
    Route::post('site/upload-banner', [SitePublicoController::class, 'uploadBanner'])->name('site.upload.banner');
    Route::delete('site/remover-banner', [SitePublicoController::class, 'removeBanner'])->name('site.remove.banner');
    Route::post('site/upload-og', [SitePublicoController::class, 'uploadOg'])->name('site.upload.og');

    Route::post('portfolio/fotos', [PortfolioController::class, 'store'])->name('portfolio.fotos.store');
    Route::delete('portfolio/fotos/{portfolioItem}', [PortfolioController::class, 'destroy'])->name('portfolio.fotos.destroy');
    Route::patch('portfolio/fotos/{portfolioItem}/toggle', [PortfolioController::class, 'toggleFeatured'])->name('portfolio.fotos.toggle');
    Route::get('clientes/buscar', [ClienteController::class, 'buscar'])->name('clientes.buscar');
    Route::get('clientes/aniversariantes', [ClienteController::class, 'aniversariantes'])->name('clientes.aniversariantes');
    Route::get('clientes/recentes', [ClienteController::class, 'recentes'])->name('clientes.recentes');
    Route::get('clientes/segmentos', [ClienteController::class, 'segmentos'])->name('clientes.segmentos');
    Route::get('clientes/exportar', [ClienteController::class, 'exportarCsv'])->name('clientes.exportar');
    Route::get('clientes/exportar/segmento', [ClienteController::class, 'exportarSegmento'])->name('clientes.exportar.segmento');
    Route::post('clientes/importar', [ClienteController::class, 'importarCsv'])->name('clientes.importar');
    Route::delete('clientes/bulk-destroy', [ClienteController::class, 'destroyBulk'])->name('clientes.bulk-destroy');
    Route::resource('clientes', ClienteController::class);
    Route::patch('clientes/{cliente}/nome', [ClienteController::class, 'nome'])->name('clientes.nome');
    Route::patch('clientes/{cliente}/toggle', [ClienteController::class, 'toggle'])->name('clientes.toggle');
    Route::patch('clientes/{cliente}/lgpd', [ClienteController::class, 'lgpd'])->name('clientes.lgpd');
    Route::patch('clientes/{cliente}/observacao', [ClienteController::class, 'observacao'])->name('clientes.observacao');
    Route::patch('clientes/{cliente}/contato', [ClienteController::class, 'contato'])->name('clientes.contato');
    Route::patch('clientes/{cliente}/nascimento', [ClienteController::class, 'nascimento'])->name('clientes.nascimento');
    Route::get('clientes/{cliente}/stats', [ClienteController::class, 'stats'])->name('clientes.stats');
    Route::get('clientes/{cliente}/frequencia', [ClienteController::class, 'frequencia'])->name('clientes.frequencia');
    Route::get('clientes/{cliente}/servicos-favoritos', [ClienteController::class, 'servicosFavoritos'])->name('clientes.servicos-favoritos');
    Route::get('clientes/{cliente}/json', [ClienteController::class, 'detalhe'])->name('clientes.detalhe');
    Route::get('clientes/{cliente}/agendamentos', [ClienteController::class, 'agendamentos'])->name('clientes.agendamentos');
    Route::get('clientes/{cliente}/proximos', [ClienteController::class, 'proximos'])->name('clientes.proximos');
    Route::get('clientes/{cliente}/compras', [ClienteController::class, 'compras'])->name('clientes.compras');
    Route::get('clientes/{cliente}/avaliacoes', [ClienteController::class, 'avaliacoes'])->name('clientes.avaliacoes');
    Route::get('clientes/{cliente}/timeline', [ClienteController::class, 'timeline'])->name('clientes.timeline');
    Route::get('clientes/{cliente}/fotos', [ClienteController::class, 'fotos'])->name('clientes.fotos.index');
    Route::post('clientes/{cliente}/fotos', [ClienteController::class, 'storeFoto'])->name('clientes.fotos.store');
    Route::delete('clientes/fotos/{foto}', [ClienteController::class, 'destroyFoto'])->name('clientes.fotos.destroy');
    Route::get('servicos/buscar', [ServicoController::class, 'buscar'])->name('servicos.buscar');
    Route::get('servicos/ativos', [ServicoController::class, 'ativos'])->name('servicos.ativos');
    Route::get('servicos/estatisticas', [ServicoController::class, 'estatisticas'])->name('servicos.estatisticas');
    Route::get('servicos/exportar', [ServicoController::class, 'exportarCsv'])->name('servicos.exportar');
    Route::resource('servicos', ServicoController::class)->except(['show']);
    Route::patch('servicos/{servico}/toggle', [ServicoController::class, 'toggle'])->name('servicos.toggle');
    Route::patch('servicos/{servico}/preco', [ServicoController::class, 'preco'])->name('servicos.preco');
    Route::patch('servicos/{servico}/duracao', [ServicoController::class, 'duracao'])->name('servicos.duracao');
    Route::patch('servicos/{servico}/cor', [ServicoController::class, 'cor'])->name('servicos.cor');
    Route::patch('servicos/{servico}/categoria', [ServicoController::class, 'categoria'])->name('servicos.categoria');
    Route::patch('servicos/{servico}/descricao', [ServicoController::class, 'descricao'])->name('servicos.descricao');
    Route::patch('servicos/{servico}/nome', [ServicoController::class, 'nome'])->name('servicos.nome');
    Route::get('servicos/{servico}/profissionais', [ServicoController::class, 'profissionais'])->name('servicos.profissionais');
    Route::get('servicos/{servico}/json', [ServicoController::class, 'detalhe'])->name('servicos.detalhe');
    Route::get('servicos/{servico}/proximos', [ServicoController::class, 'proximos'])->name('servicos.proximos');
    Route::get('servicos/{servico}/avaliacoes', [ServicoController::class, 'avaliacoes'])->name('servicos.avaliacoes');
    Route::get('profissionais/buscar', [ProfissionalController::class, 'buscar'])->name('profissionais.buscar');
    Route::get('profissionais/sem-cargo', [ProfissionalController::class, 'semCargo'])->name('profissionais.sem-cargo');
    Route::get('profissionais/ranking', [ProfissionalController::class, 'ranking'])->name('profissionais.ranking');
    Route::get('profissionais/exportar', [ProfissionalController::class, 'exportarCsv'])->name('profissionais.exportar');
    Route::resource('profissionais', ProfissionalController::class)->parameters(['profissionais' => 'profissional']);
    Route::patch('profissionais/{profissional}/toggle', [ProfissionalController::class, 'toggle'])->name('profissionais.toggle');
    Route::get('profissionais/{profissional}/disponibilidade', [ProfissionalController::class, 'disponibilidade'])->name('profissionais.disponibilidade');
    Route::get('profissionais/{profissional}/servicos', [ProfissionalController::class, 'servicos'])->name('profissionais.servicos');
    Route::get('profissionais/{profissional}/agendamentos', [ProfissionalController::class, 'agendamentos'])->name('profissionais.agendamentos');
    Route::get('profissionais/{profissional}/proximos', [ProfissionalController::class, 'proximos'])->name('profissionais.proximos');
    Route::get('profissionais/{profissional}/vendas', [ProfissionalController::class, 'vendas'])->name('profissionais.vendas');
    Route::get('profissionais/{profissional}/avaliacoes', [ProfissionalController::class, 'avaliacoes'])->name('profissionais.avaliacoes');
    Route::get('profissionais/{profissional}/json', [ProfissionalController::class, 'detalhe'])->name('profissionais.detalhe');
    Route::get('profissionais/{profissional}/stats', [ProfissionalController::class, 'stats'])->name('profissionais.stats');
    Route::patch('profissionais/{profissional}/comissao', [ProfissionalController::class, 'comissao'])->name('profissionais.comissao');
    Route::patch('profissionais/{profissional}/cor', [ProfissionalController::class, 'cor'])->name('profissionais.cor');
    Route::patch('profissionais/{profissional}/especialidade', [ProfissionalController::class, 'especialidade'])->name('profissionais.especialidade');
    Route::patch('profissionais/{profissional}/contato', [ProfissionalController::class, 'contato'])->name('profissionais.contato');
    Route::patch('profissionais/{profissional}/admissao', [ProfissionalController::class, 'admissao'])->name('profissionais.admissao');
    Route::patch('profissionais/{profissional}/cargo', [ProfissionalController::class, 'cargo'])->name('profissionais.cargo');
    Route::patch('profissionais/{profissional}/nome', [ProfissionalController::class, 'nome'])->name('profissionais.nome');
    Route::post('profissionais/{profissional}/foto', [ProfissionalController::class, 'uploadFoto'])->name('profissionais.foto.upload');
    Route::delete('profissionais/{profissional}/foto', [ProfissionalController::class, 'deleteFoto'])->name('profissionais.foto.delete');
    Route::get('profissionais/{profissional}/horarios', [HorarioTrabalhoController::class, 'show'])->name('profissionais.horarios');
    Route::put('profissionais/{profissional}/horarios', [HorarioTrabalhoController::class, 'update'])->name('profissionais.horarios.update');
    Route::get('profissionais/{profissional}/bloqueios', [BloqueioController::class, 'index'])->name('profissionais.bloqueios.index');
    Route::post('profissionais/{profissional}/bloqueios', [BloqueioController::class, 'store'])->name('profissionais.bloqueios.store');
    Route::patch('bloqueios/{bloqueio}', [BloqueioController::class, 'update'])->name('bloqueios.update');
    Route::delete('bloqueios/{bloqueio}', [BloqueioController::class, 'destroy'])->name('bloqueios.destroy');

    Route::get('perfil', [PerfilController::class, 'show'])->name('perfil');
    Route::put('perfil', [PerfilController::class, 'update'])->name('perfil.update');

    Route::get('configuracoes', [ConfiguracaoController::class, 'show'])->name('configuracoes');
    Route::put('configuracoes/preferencias', [ConfiguracaoController::class, 'updatePreferencias'])->name('configuracoes.preferencias');
    Route::post('configuracoes/tipografia', [ConfiguracaoController::class, 'updateTipografia'])->name('configuracoes.tipografia');
    Route::post('configuracoes/preferencias/restaurar-tipografia', [ConfiguracaoController::class, 'resetTipografia'])->name('configuracoes.tipografia.reset');
    Route::get('configuracoes/empresa/stats', [ConfiguracaoController::class, 'empresaStats'])->name('configuracoes.empresa.stats');
    Route::get('configuracoes/empresa', [ConfiguracaoController::class, 'empresa'])->name('configuracoes.empresa');
    Route::get('configuracoes/empresa/qrcode', [ConfiguracaoController::class, 'qrCode'])->name('configuracoes.empresa.qrcode');
    Route::put('configuracoes/empresa', [ConfiguracaoController::class, 'updateEmpresa'])->name('configuracoes.empresa.update');
    Route::post('configuracoes/empresa/logo', [ConfiguracaoController::class, 'uploadLogo'])->name('configuracoes.empresa.logo.upload');
    Route::delete('configuracoes/empresa/logo', [ConfiguracaoController::class, 'deleteLogo'])->name('configuracoes.empresa.logo.delete');

    Route::get('planos', [PlansController::class, 'index'])->name('planos.index');
    Route::patch('planos', [PlansController::class, 'update'])->name('planos.update');

    Route::get('notificacoes', [NotificacaoController::class, 'index'])->name('notificacoes.index');
    Route::get('notificacoes/unread-count', [NotificacaoController::class, 'unreadCount'])->name('notificacoes.unread-count');
    Route::patch('notificacoes/todas-lidas', [NotificacaoController::class, 'markAllRead'])->name('notificacoes.todas-lidas');
    Route::patch('notificacoes/{notificacao}/lida', [NotificacaoController::class, 'markRead'])->name('notificacoes.lida');
    Route::delete('notificacoes/{notificacao}', [NotificacaoController::class, 'destroy'])->name('notificacoes.destroy');
});

// Agendamento público — sem autenticação
Route::get('/vitrine/{slug}', [AgendamentoPublicoController::class, 'landing'])->name('vitrine.show');
Route::get('/vitrine/{slug}/disponibilidade', [AgendamentoPublicoController::class, 'disponibilidade'])->name('vitrine.disponibilidade');
Route::get('/agendar/{slug}', [AgendamentoPublicoController::class, 'show'])->name('agendar.show');
Route::post('/agendar/{slug}', [AgendamentoPublicoController::class, 'store'])->name('agendar.store');
Route::get('/agendar/{slug}/slots', [AgendamentoPublicoController::class, 'slots'])->name('agendar.slots');
Route::get('/agendar/{slug}/confirmado/{agendamento}', [AgendamentoPublicoController::class, 'confirmado'])->name('agendar.confirmado');
Route::get('/vitrine/{slug}/minhas-reservas', [AgendamentoPublicoController::class, 'minhasReservas'])->name('vitrine.minhas-reservas');
Route::get('/meu-agendamento/{token}', [AgendamentoPublicoController::class, 'meuAgendamento'])->name('agendamento.meu');
Route::post('/meu-agendamento/{token}/cancelar', [AgendamentoPublicoController::class, 'cancelarMeuAgendamento'])->name('agendamento.cancelar');
Route::get('/avaliar/{token}', [AvaliacaoController::class, 'show'])->name('avaliacao.show');
Route::post('/avaliar/{token}', [AvaliacaoController::class, 'store'])->name('avaliacao.store');

if (app()->isLocal()) {
    Route::post('/dev/login', [DevLoginController::class, 'login'])->name('dev.login');
}
